#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Template1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HocPhi")]
	public partial class QLHPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertNganh(Nganh instance);
    partial void UpdateNganh(Nganh instance);
    partial void DeleteNganh(Nganh instance);
    partial void InsertSinh_vien(Sinh_vien instance);
    partial void UpdateSinh_vien(Sinh_vien instance);
    partial void DeleteSinh_vien(Sinh_vien instance);
    partial void InsertPhieu_Nop(Phieu_Nop instance);
    partial void UpdatePhieu_Nop(Phieu_Nop instance);
    partial void DeletePhieu_Nop(Phieu_Nop instance);
    #endregion
		
		public QLHPDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HocPhiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<Nganh> Nganhs
		{
			get
			{
				return this.GetTable<Nganh>();
			}
		}
		
		public System.Data.Linq.Table<Sinh_vien> Sinh_viens
		{
			get
			{
				return this.GetTable<Sinh_vien>();
			}
		}
		
		public System.Data.Linq.Table<Phieu_Nop> Phieu_Nops
		{
			get
			{
				return this.GetTable<Phieu_Nop>();
			}
		}
		
		public System.Data.Linq.Table<V_DSNop> V_DSNops
		{
			get
			{
				return this.GetTable<V_DSNop>();
			}
		}
		
		public System.Data.Linq.Table<V_TongTienTheoLop> V_TongTienTheoLops
		{
			get
			{
				return this.GetTable<V_TongTienTheoLop>();
			}
		}
		
		public System.Data.Linq.Table<V_TongTienTheoNganh> V_TongTienTheoNganhs
		{
			get
			{
				return this.GetTable<V_TongTienTheoNganh>();
			}
		}
		
		public System.Data.Linq.Table<V_TongTienTheoNgay> V_TongTienTheoNgays
		{
			get
			{
				return this.GetTable<V_TongTienTheoNgay>();
			}
		}
		
		public System.Data.Linq.Table<V_TongTienTheoSinhVien> V_TongTienTheoSinhViens
		{
			get
			{
				return this.GetTable<V_TongTienTheoSinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Lop;
		
		private string _Ten_Lop;
		
		private string _Ma_Nganh;
		
		private EntitySet<Sinh_vien> _Sinh_viens;
		
		private EntityRef<Nganh> _Nganh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_LopChanging(string value);
    partial void OnMa_LopChanged();
    partial void OnTen_LopChanging(string value);
    partial void OnTen_LopChanged();
    partial void OnMa_NganhChanging(string value);
    partial void OnMa_NganhChanged();
    #endregion
		
		public Lop()
		{
			this._Sinh_viens = new EntitySet<Sinh_vien>(new Action<Sinh_vien>(this.attach_Sinh_viens), new Action<Sinh_vien>(this.detach_Sinh_viens));
			this._Nganh = default(EntityRef<Nganh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Lop", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Lop
		{
			get
			{
				return this._Ma_Lop;
			}
			set
			{
				if ((this._Ma_Lop != value))
				{
					this.OnMa_LopChanging(value);
					this.SendPropertyChanging();
					this._Ma_Lop = value;
					this.SendPropertyChanged("Ma_Lop");
					this.OnMa_LopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Lop", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ten_Lop
		{
			get
			{
				return this._Ten_Lop;
			}
			set
			{
				if ((this._Ten_Lop != value))
				{
					this.OnTen_LopChanging(value);
					this.SendPropertyChanging();
					this._Ten_Lop = value;
					this.SendPropertyChanged("Ten_Lop");
					this.OnTen_LopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Nganh", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_Nganh
		{
			get
			{
				return this._Ma_Nganh;
			}
			set
			{
				if ((this._Ma_Nganh != value))
				{
					if (this._Nganh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_NganhChanging(value);
					this.SendPropertyChanging();
					this._Ma_Nganh = value;
					this.SendPropertyChanged("Ma_Nganh");
					this.OnMa_NganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_Sinh_vien", Storage="_Sinh_viens", ThisKey="Ma_Lop", OtherKey="Ma_Lop")]
		public EntitySet<Sinh_vien> Sinh_viens
		{
			get
			{
				return this._Sinh_viens;
			}
			set
			{
				this._Sinh_viens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nganh_Lop", Storage="_Nganh", ThisKey="Ma_Nganh", OtherKey="Ma_Nganh", IsForeignKey=true)]
		public Nganh Nganh
		{
			get
			{
				return this._Nganh.Entity;
			}
			set
			{
				Nganh previousValue = this._Nganh.Entity;
				if (((previousValue != value) 
							|| (this._Nganh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nganh.Entity = null;
						previousValue.Lops.Remove(this);
					}
					this._Nganh.Entity = value;
					if ((value != null))
					{
						value.Lops.Add(this);
						this._Ma_Nganh = value.Ma_Nganh;
					}
					else
					{
						this._Ma_Nganh = default(string);
					}
					this.SendPropertyChanged("Nganh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sinh_viens(Sinh_vien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_Sinh_viens(Sinh_vien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nganh")]
	public partial class Nganh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_Nganh;
		
		private string _Ten_Nganh;
		
		private EntitySet<Lop> _Lops;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_NganhChanging(string value);
    partial void OnMa_NganhChanged();
    partial void OnTen_NganhChanging(string value);
    partial void OnTen_NganhChanged();
    #endregion
		
		public Nganh()
		{
			this._Lops = new EntitySet<Lop>(new Action<Lop>(this.attach_Lops), new Action<Lop>(this.detach_Lops));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Nganh", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_Nganh
		{
			get
			{
				return this._Ma_Nganh;
			}
			set
			{
				if ((this._Ma_Nganh != value))
				{
					this.OnMa_NganhChanging(value);
					this.SendPropertyChanging();
					this._Ma_Nganh = value;
					this.SendPropertyChanged("Ma_Nganh");
					this.OnMa_NganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Nganh", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ten_Nganh
		{
			get
			{
				return this._Ten_Nganh;
			}
			set
			{
				if ((this._Ten_Nganh != value))
				{
					this.OnTen_NganhChanging(value);
					this.SendPropertyChanging();
					this._Ten_Nganh = value;
					this.SendPropertyChanged("Ten_Nganh");
					this.OnTen_NganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nganh_Lop", Storage="_Lops", ThisKey="Ma_Nganh", OtherKey="Ma_Nganh")]
		public EntitySet<Lop> Lops
		{
			get
			{
				return this._Lops;
			}
			set
			{
				this._Lops.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.Nganh = this;
		}
		
		private void detach_Lops(Lop entity)
		{
			this.SendPropertyChanging();
			entity.Nganh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Sinh vien]")]
	public partial class Sinh_vien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_SV;
		
		private string _Ma_Lop;
		
		private string _Ho_Ten;
		
		private System.DateTime _Ngay_Sinh;
		
		private string _Gioi_Tinh;
		
		private string _Khoa_Hoc;
		
		private EntitySet<Phieu_Nop> _Phieu_Nops;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    partial void OnMa_LopChanging(string value);
    partial void OnMa_LopChanged();
    partial void OnHo_TenChanging(string value);
    partial void OnHo_TenChanged();
    partial void OnNgay_SinhChanging(System.DateTime value);
    partial void OnNgay_SinhChanged();
    partial void OnGioi_TinhChanging(string value);
    partial void OnGioi_TinhChanged();
    partial void OnKhoa_HocChanging(string value);
    partial void OnKhoa_HocChanged();
    #endregion
		
		public Sinh_vien()
		{
			this._Phieu_Nops = new EntitySet<Phieu_Nop>(new Action<Phieu_Nop>(this.attach_Phieu_Nops), new Action<Phieu_Nop>(this.detach_Phieu_Nops));
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Lop", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_Lop
		{
			get
			{
				return this._Ma_Lop;
			}
			set
			{
				if ((this._Ma_Lop != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_LopChanging(value);
					this.SendPropertyChanging();
					this._Ma_Lop = value;
					this.SendPropertyChanged("Ma_Lop");
					this.OnMa_LopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ho_Ten
		{
			get
			{
				return this._Ho_Ten;
			}
			set
			{
				if ((this._Ho_Ten != value))
				{
					this.OnHo_TenChanging(value);
					this.SendPropertyChanging();
					this._Ho_Ten = value;
					this.SendPropertyChanged("Ho_Ten");
					this.OnHo_TenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Sinh", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_Sinh
		{
			get
			{
				return this._Ngay_Sinh;
			}
			set
			{
				if ((this._Ngay_Sinh != value))
				{
					this.OnNgay_SinhChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Sinh = value;
					this.SendPropertyChanged("Ngay_Sinh");
					this.OnNgay_SinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_Tinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Gioi_Tinh
		{
			get
			{
				return this._Gioi_Tinh;
			}
			set
			{
				if ((this._Gioi_Tinh != value))
				{
					this.OnGioi_TinhChanging(value);
					this.SendPropertyChanging();
					this._Gioi_Tinh = value;
					this.SendPropertyChanged("Gioi_Tinh");
					this.OnGioi_TinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa_Hoc", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Khoa_Hoc
		{
			get
			{
				return this._Khoa_Hoc;
			}
			set
			{
				if ((this._Khoa_Hoc != value))
				{
					this.OnKhoa_HocChanging(value);
					this.SendPropertyChanging();
					this._Khoa_Hoc = value;
					this.SendPropertyChanged("Khoa_Hoc");
					this.OnKhoa_HocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinh_vien_Phieu_Nop", Storage="_Phieu_Nops", ThisKey="Ma_SV", OtherKey="Ma_SV")]
		public EntitySet<Phieu_Nop> Phieu_Nops
		{
			get
			{
				return this._Phieu_Nops;
			}
			set
			{
				this._Phieu_Nops.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_Sinh_vien", Storage="_Lop", ThisKey="Ma_Lop", OtherKey="Ma_Lop", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.Sinh_viens.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.Sinh_viens.Add(this);
						this._Ma_Lop = value.Ma_Lop;
					}
					else
					{
						this._Ma_Lop = default(string);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phieu_Nops(Phieu_Nop entity)
		{
			this.SendPropertyChanging();
			entity.Sinh_vien = this;
		}
		
		private void detach_Phieu_Nops(Phieu_Nop entity)
		{
			this.SendPropertyChanging();
			entity.Sinh_vien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Phieu Nop]")]
	public partial class Phieu_Nop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_So_Phieu;
		
		private string _Ma_SV;
		
		private System.DateTime _Ngay_Nap;
		
		private double _So_Tien;
		
		private EntityRef<Sinh_vien> _Sinh_vien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_So_PhieuChanging(string value);
    partial void OnMa_So_PhieuChanged();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    partial void OnNgay_NapChanging(System.DateTime value);
    partial void OnNgay_NapChanged();
    partial void OnSo_TienChanging(double value);
    partial void OnSo_TienChanged();
    #endregion
		
		public Phieu_Nop()
		{
			this._Sinh_vien = default(EntityRef<Sinh_vien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_So_Phieu", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_So_Phieu
		{
			get
			{
				return this._Ma_So_Phieu;
			}
			set
			{
				if ((this._Ma_So_Phieu != value))
				{
					this.OnMa_So_PhieuChanging(value);
					this.SendPropertyChanging();
					this._Ma_So_Phieu = value;
					this.SendPropertyChanged("Ma_So_Phieu");
					this.OnMa_So_PhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					if (this._Sinh_vien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Nap", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_Nap
		{
			get
			{
				return this._Ngay_Nap;
			}
			set
			{
				if ((this._Ngay_Nap != value))
				{
					this.OnNgay_NapChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Nap = value;
					this.SendPropertyChanged("Ngay_Nap");
					this.OnNgay_NapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Tien", DbType="Float NOT NULL")]
		public double So_Tien
		{
			get
			{
				return this._So_Tien;
			}
			set
			{
				if ((this._So_Tien != value))
				{
					this.OnSo_TienChanging(value);
					this.SendPropertyChanging();
					this._So_Tien = value;
					this.SendPropertyChanged("So_Tien");
					this.OnSo_TienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinh_vien_Phieu_Nop", Storage="_Sinh_vien", ThisKey="Ma_SV", OtherKey="Ma_SV", IsForeignKey=true)]
		public Sinh_vien Sinh_vien
		{
			get
			{
				return this._Sinh_vien.Entity;
			}
			set
			{
				Sinh_vien previousValue = this._Sinh_vien.Entity;
				if (((previousValue != value) 
							|| (this._Sinh_vien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sinh_vien.Entity = null;
						previousValue.Phieu_Nops.Remove(this);
					}
					this._Sinh_vien.Entity = value;
					if ((value != null))
					{
						value.Phieu_Nops.Add(this);
						this._Ma_SV = value.Ma_SV;
					}
					else
					{
						this._Ma_SV = default(string);
					}
					this.SendPropertyChanged("Sinh_vien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_DSNop")]
	public partial class V_DSNop
	{
		
		private string _Ma_So_Phieu;
		
		private string _Ma_SV;
		
		private string _Ho_Ten;
		
		private System.DateTime _Ngay_Sinh;
		
		private string _Gioi_Tinh;
		
		private string _Khoa_Hoc;
		
		private string _Ma_Lop;
		
		private string _Ten_Lop;
		
		private string _Ma_Nganh;
		
		private string _Ten_Nganh;
		
		private double _So_Tien;
		
		private System.DateTime _Ngay_Nap;
		
		public V_DSNop()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_So_Phieu", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_So_Phieu
		{
			get
			{
				return this._Ma_So_Phieu;
			}
			set
			{
				if ((this._Ma_So_Phieu != value))
				{
					this._Ma_So_Phieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					this._Ma_SV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ho_Ten
		{
			get
			{
				return this._Ho_Ten;
			}
			set
			{
				if ((this._Ho_Ten != value))
				{
					this._Ho_Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Sinh", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_Sinh
		{
			get
			{
				return this._Ngay_Sinh;
			}
			set
			{
				if ((this._Ngay_Sinh != value))
				{
					this._Ngay_Sinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_Tinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Gioi_Tinh
		{
			get
			{
				return this._Gioi_Tinh;
			}
			set
			{
				if ((this._Gioi_Tinh != value))
				{
					this._Gioi_Tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa_Hoc", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Khoa_Hoc
		{
			get
			{
				return this._Khoa_Hoc;
			}
			set
			{
				if ((this._Khoa_Hoc != value))
				{
					this._Khoa_Hoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Lop", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_Lop
		{
			get
			{
				return this._Ma_Lop;
			}
			set
			{
				if ((this._Ma_Lop != value))
				{
					this._Ma_Lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Lop", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ten_Lop
		{
			get
			{
				return this._Ten_Lop;
			}
			set
			{
				if ((this._Ten_Lop != value))
				{
					this._Ten_Lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Nganh", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_Nganh
		{
			get
			{
				return this._Ma_Nganh;
			}
			set
			{
				if ((this._Ma_Nganh != value))
				{
					this._Ma_Nganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Nganh", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ten_Nganh
		{
			get
			{
				return this._Ten_Nganh;
			}
			set
			{
				if ((this._Ten_Nganh != value))
				{
					this._Ten_Nganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_Tien", DbType="Float NOT NULL")]
		public double So_Tien
		{
			get
			{
				return this._So_Tien;
			}
			set
			{
				if ((this._So_Tien != value))
				{
					this._So_Tien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Nap", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_Nap
		{
			get
			{
				return this._Ngay_Nap;
			}
			set
			{
				if ((this._Ngay_Nap != value))
				{
					this._Ngay_Nap = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_TongTienTheoLop")]
	public partial class V_TongTienTheoLop
	{
		
		private string _Ma_Lop;
		
		private System.Nullable<double> _Tong_Tien;
		
		public V_TongTienTheoLop()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_Lop", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_Lop
		{
			get
			{
				return this._Ma_Lop;
			}
			set
			{
				if ((this._Ma_Lop != value))
				{
					this._Ma_Lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_Tien", DbType="Float")]
		public System.Nullable<double> Tong_Tien
		{
			get
			{
				return this._Tong_Tien;
			}
			set
			{
				if ((this._Tong_Tien != value))
				{
					this._Tong_Tien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_TongTienTheoNganh")]
	public partial class V_TongTienTheoNganh
	{
		
		private string _Ten_Nganh;
		
		private System.Nullable<double> _Tong_Tien;
		
		public V_TongTienTheoNganh()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Nganh", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ten_Nganh
		{
			get
			{
				return this._Ten_Nganh;
			}
			set
			{
				if ((this._Ten_Nganh != value))
				{
					this._Ten_Nganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_Tien", DbType="Float")]
		public System.Nullable<double> Tong_Tien
		{
			get
			{
				return this._Tong_Tien;
			}
			set
			{
				if ((this._Tong_Tien != value))
				{
					this._Tong_Tien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_TongTienTheoNgay")]
	public partial class V_TongTienTheoNgay
	{
		
		private System.DateTime _Ngay_Nap;
		
		private System.Nullable<double> _Tong_Tien;
		
		public V_TongTienTheoNgay()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Nap", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_Nap
		{
			get
			{
				return this._Ngay_Nap;
			}
			set
			{
				if ((this._Ngay_Nap != value))
				{
					this._Ngay_Nap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_Tien", DbType="Float")]
		public System.Nullable<double> Tong_Tien
		{
			get
			{
				return this._Tong_Tien;
			}
			set
			{
				if ((this._Tong_Tien != value))
				{
					this._Tong_Tien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_TongTienTheoSinhVien")]
	public partial class V_TongTienTheoSinhVien
	{
		
		private string _Ma_SV;
		
		private string _Ho_Ten;
		
		private System.DateTime _Ngay_Sinh;
		
		private string _Gioi_Tinh;
		
		private string _Khoa_Hoc;
		
		private string _Ten_Lop;
		
		private string _Ten_Nganh;
		
		private System.Nullable<double> _Tong_Tien;
		
		public V_TongTienTheoSinhVien()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					this._Ma_SV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_Ten", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ho_Ten
		{
			get
			{
				return this._Ho_Ten;
			}
			set
			{
				if ((this._Ho_Ten != value))
				{
					this._Ho_Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Sinh", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_Sinh
		{
			get
			{
				return this._Ngay_Sinh;
			}
			set
			{
				if ((this._Ngay_Sinh != value))
				{
					this._Ngay_Sinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_Tinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Gioi_Tinh
		{
			get
			{
				return this._Gioi_Tinh;
			}
			set
			{
				if ((this._Gioi_Tinh != value))
				{
					this._Gioi_Tinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa_Hoc", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string Khoa_Hoc
		{
			get
			{
				return this._Khoa_Hoc;
			}
			set
			{
				if ((this._Khoa_Hoc != value))
				{
					this._Khoa_Hoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Lop", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ten_Lop
		{
			get
			{
				return this._Ten_Lop;
			}
			set
			{
				if ((this._Ten_Lop != value))
				{
					this._Ten_Lop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Nganh", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Ten_Nganh
		{
			get
			{
				return this._Ten_Nganh;
			}
			set
			{
				if ((this._Ten_Nganh != value))
				{
					this._Ten_Nganh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_Tien", DbType="Float")]
		public System.Nullable<double> Tong_Tien
		{
			get
			{
				return this._Tong_Tien;
			}
			set
			{
				if ((this._Tong_Tien != value))
				{
					this._Tong_Tien = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
