//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceSoapQLHP.DSSV {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sinh_vien", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sinh_vien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ma_SVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ma_LopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ho_TenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ngay_SinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Khoa_HocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceSoapQLHP.DSSV.Phieu_Nop[] Phieu_NopsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceSoapQLHP.DSSV.Lop LopField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ma_SV {
            get {
                return this.Ma_SVField;
            }
            set {
                if ((object.ReferenceEquals(this.Ma_SVField, value) != true)) {
                    this.Ma_SVField = value;
                    this.RaisePropertyChanged("Ma_SV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ma_Lop {
            get {
                return this.Ma_LopField;
            }
            set {
                if ((object.ReferenceEquals(this.Ma_LopField, value) != true)) {
                    this.Ma_LopField = value;
                    this.RaisePropertyChanged("Ma_Lop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ho_Ten {
            get {
                return this.Ho_TenField;
            }
            set {
                if ((object.ReferenceEquals(this.Ho_TenField, value) != true)) {
                    this.Ho_TenField = value;
                    this.RaisePropertyChanged("Ho_Ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ngay_Sinh {
            get {
                return this.Ngay_SinhField;
            }
            set {
                if ((object.ReferenceEquals(this.Ngay_SinhField, value) != true)) {
                    this.Ngay_SinhField = value;
                    this.RaisePropertyChanged("Ngay_Sinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Khoa_Hoc {
            get {
                return this.Khoa_HocField;
            }
            set {
                if ((object.ReferenceEquals(this.Khoa_HocField, value) != true)) {
                    this.Khoa_HocField = value;
                    this.RaisePropertyChanged("Khoa_Hoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WebServiceSoapQLHP.DSSV.Phieu_Nop[] Phieu_Nops {
            get {
                return this.Phieu_NopsField;
            }
            set {
                if ((object.ReferenceEquals(this.Phieu_NopsField, value) != true)) {
                    this.Phieu_NopsField = value;
                    this.RaisePropertyChanged("Phieu_Nops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WebServiceSoapQLHP.DSSV.Lop Lop {
            get {
                return this.LopField;
            }
            set {
                if ((object.ReferenceEquals(this.LopField, value) != true)) {
                    this.LopField = value;
                    this.RaisePropertyChanged("Lop");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lop", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Lop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ma_LopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ma_NganhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceSoapQLHP.DSSV.Sinh_vien[] Sinh_viensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceSoapQLHP.DSSV.Nganh NganhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ma_Lop {
            get {
                return this.Ma_LopField;
            }
            set {
                if ((object.ReferenceEquals(this.Ma_LopField, value) != true)) {
                    this.Ma_LopField = value;
                    this.RaisePropertyChanged("Ma_Lop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ma_Nganh {
            get {
                return this.Ma_NganhField;
            }
            set {
                if ((object.ReferenceEquals(this.Ma_NganhField, value) != true)) {
                    this.Ma_NganhField = value;
                    this.RaisePropertyChanged("Ma_Nganh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebServiceSoapQLHP.DSSV.Sinh_vien[] Sinh_viens {
            get {
                return this.Sinh_viensField;
            }
            set {
                if ((object.ReferenceEquals(this.Sinh_viensField, value) != true)) {
                    this.Sinh_viensField = value;
                    this.RaisePropertyChanged("Sinh_viens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebServiceSoapQLHP.DSSV.Nganh Nganh {
            get {
                return this.NganhField;
            }
            set {
                if ((object.ReferenceEquals(this.NganhField, value) != true)) {
                    this.NganhField = value;
                    this.RaisePropertyChanged("Nganh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phieu_Nop", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Phieu_Nop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string So_PhieuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ma_SVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ngay_NapField;
        
        private double So_TienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceSoapQLHP.DSSV.Sinh_vien Sinh_vienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string So_Phieu {
            get {
                return this.So_PhieuField;
            }
            set {
                if ((object.ReferenceEquals(this.So_PhieuField, value) != true)) {
                    this.So_PhieuField = value;
                    this.RaisePropertyChanged("So_Phieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ma_SV {
            get {
                return this.Ma_SVField;
            }
            set {
                if ((object.ReferenceEquals(this.Ma_SVField, value) != true)) {
                    this.Ma_SVField = value;
                    this.RaisePropertyChanged("Ma_SV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ngay_Nap {
            get {
                return this.Ngay_NapField;
            }
            set {
                if ((object.ReferenceEquals(this.Ngay_NapField, value) != true)) {
                    this.Ngay_NapField = value;
                    this.RaisePropertyChanged("Ngay_Nap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double So_Tien {
            get {
                return this.So_TienField;
            }
            set {
                if ((this.So_TienField.Equals(value) != true)) {
                    this.So_TienField = value;
                    this.RaisePropertyChanged("So_Tien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WebServiceSoapQLHP.DSSV.Sinh_vien Sinh_vien {
            get {
                return this.Sinh_vienField;
            }
            set {
                if ((object.ReferenceEquals(this.Sinh_vienField, value) != true)) {
                    this.Sinh_vienField = value;
                    this.RaisePropertyChanged("Sinh_vien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nganh", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Nganh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ma_NganhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ten_NganhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceSoapQLHP.DSSV.Lop[] LopsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ma_Nganh {
            get {
                return this.Ma_NganhField;
            }
            set {
                if ((object.ReferenceEquals(this.Ma_NganhField, value) != true)) {
                    this.Ma_NganhField = value;
                    this.RaisePropertyChanged("Ma_Nganh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ten_Nganh {
            get {
                return this.Ten_NganhField;
            }
            set {
                if ((object.ReferenceEquals(this.Ten_NganhField, value) != true)) {
                    this.Ten_NganhField = value;
                    this.RaisePropertyChanged("Ten_Nganh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebServiceSoapQLHP.DSSV.Lop[] Lops {
            get {
                return this.LopsField;
            }
            set {
                if ((object.ReferenceEquals(this.LopsField, value) != true)) {
                    this.LopsField = value;
                    this.RaisePropertyChanged("Lops");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DSSV.QLHPSoap")]
    public interface QLHPSoap {
        
        // CODEGEN: Generating message contract since element name DanhsachSVResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DanhsachSV", ReplyAction="*")]
        WebServiceSoapQLHP.DSSV.DanhsachSVResponse DanhsachSV(WebServiceSoapQLHP.DSSV.DanhsachSVRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhsachSVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhsachSV", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceSoapQLHP.DSSV.DanhsachSVRequestBody Body;
        
        public DanhsachSVRequest() {
        }
        
        public DanhsachSVRequest(WebServiceSoapQLHP.DSSV.DanhsachSVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DanhsachSVRequestBody {
        
        public DanhsachSVRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DanhsachSVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DanhsachSVResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceSoapQLHP.DSSV.DanhsachSVResponseBody Body;
        
        public DanhsachSVResponse() {
        }
        
        public DanhsachSVResponse(WebServiceSoapQLHP.DSSV.DanhsachSVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DanhsachSVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceSoapQLHP.DSSV.Sinh_vien[] DanhsachSVResult;
        
        public DanhsachSVResponseBody() {
        }
        
        public DanhsachSVResponseBody(WebServiceSoapQLHP.DSSV.Sinh_vien[] DanhsachSVResult) {
            this.DanhsachSVResult = DanhsachSVResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QLHPSoapChannel : WebServiceSoapQLHP.DSSV.QLHPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QLHPSoapClient : System.ServiceModel.ClientBase<WebServiceSoapQLHP.DSSV.QLHPSoap>, WebServiceSoapQLHP.DSSV.QLHPSoap {
        
        public QLHPSoapClient() {
        }
        
        public QLHPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QLHPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLHPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QLHPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceSoapQLHP.DSSV.DanhsachSVResponse WebServiceSoapQLHP.DSSV.QLHPSoap.DanhsachSV(WebServiceSoapQLHP.DSSV.DanhsachSVRequest request) {
            return base.Channel.DanhsachSV(request);
        }
        
        public WebServiceSoapQLHP.DSSV.Sinh_vien[] DanhsachSV() {
            WebServiceSoapQLHP.DSSV.DanhsachSVRequest inValue = new WebServiceSoapQLHP.DSSV.DanhsachSVRequest();
            inValue.Body = new WebServiceSoapQLHP.DSSV.DanhsachSVRequestBody();
            WebServiceSoapQLHP.DSSV.DanhsachSVResponse retVal = ((WebServiceSoapQLHP.DSSV.QLHPSoap)(this)).DanhsachSV(inValue);
            return retVal.Body.DanhsachSVResult;
        }
    }
}
